FROM openjdk:11
WORKDIR usr/src
ADD ./target/springbootzuulgatewayproxy-0.0.1-SNAPSHOT.jar /usr/src/springbootzuulgatewayproxy-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springbootzuulgatewayproxy-0.0.1-SNAPSHOT.jar"]
